export const data = [
  {
    id:1,
    img:"prod1.webp",
    prodName:"Nike Air Jordan Men Cotton T shirt",
    desc:"Graphic Logo Crew Black Tshirt Tee S M L XL",
    price:"RS.800",
  },
  {
    id:2,
    img:"prod2.webp",
    prodName:"Nike Men's Air Jordan T-Shirt ",
    desc:"100% Cotton Jordan Air Wordmark T-Shirt",
    price:"RS.500",
  },
  {
    id:3,
    img:"prod3.webp",
    prodName:"Nike Dri-Fit Short Sleeve Shirt Men's",
    desc:"Orange New with Tags",
    price:"RS.5000",
  },
  {
    id:4,
    img:"prod4.webp",
    prodName:"Nike Men's Sportswear Active Short Sleeve T-Shirt ",
    desc:"Black/White, AR5004-010",
    price:"RS.500",
  },
  {
    id:5,
    img:"prod5.webp",
    prodName:"Nike DRI-FIT Miler Run Shirt",
    desc:"Size M-XL Men Blue CU0326-480 *NWT ",
    price:"RS.800",
  },{
    id:6,
    img:"prod6.webp",
    prodName:"UConn Huskies Nike Pro Dri-Fit",
    desc:"Sleeveless Shirt Men's Red New without Tags",
    price:"RS.5050",
  },
  {
    id:7,
    img:"prod7.webp",
    prodName:"Nike Brasil Soccer Shirt",
    desc:"Mens Slim Fit 547212 Brazilian Football Team T Shirt",
    price:"RS.2000",
  },
  {
    id:8,
    img:"prod1.jpg",
    prodName:"NWT Nike Medium Men Sportswear Tee Shirt ",
    desc:"Loose Fit Full Sleeve with Drop Shoulder Round Neck Women's Sweatshirt",
    price:"RS.5000",
  },
  {
    id:9,
    img:"prod1.jpg",
    prodName:"LEOTUDE",
    desc:"Loose Fit Full Sleeve with Drop Shoulder Round Neck Women's Sweatshirt",
    price:"RS.500",
  },
  {
    id:10,
    img:"prod1.jpg",
    prodName:"LEOTUDE",
    desc:"Loose Fit Full Sleeve with Drop Shoulder Round Neck Women's Sweatshirt",
    price:"RS.500",
  },
  {
    id:11,
    img:"prod1.jpg",
    prodName:"LEOTUDE",
    desc:"Loose Fit Full Sleeve with Drop Shoulder Round Neck Women's Sweatshirt",
    price:"RS.500",
  },
]